/**
 * Company facts researched from hxhdchemical.com (about-us, news archive) and
 * verified 2026-08-09. Every figure below is sourced — do not add numbers here
 * that cannot be traced to `source`.
 */

export interface ProductionBase {
  entity: string;
  city: string;
  country: 'China' | 'Bangladesh';
  note?: string;
  primary?: boolean;
}

export const COMPANY = {
  group: 'Hongxing Hongda',
  legalName: 'Hubei Hongxing Hongda New Materials Co., Ltd.',
  founded: 2000,
  headOffice:
    '9B, West Liando U Valley, Majuqiao Town, Tongzhou District, Beijing, China',
  phone: '+86 137 1827 5936',
  phoneHref: '+8613718275936',
  /**
   * Designated enquiry address for this site. Import COMPANY.email rather than
   * hardcoding it — every page, form and footer reads from here.
   * (The address published on hxhdchemical.com is hxhdchem@163.com; this
   * inbox supersedes it for enquiries generated by this site.)
   */
  email: 'hongxinghongda7@gmail.com',
  sourceUrl: 'https://www.hxhdchemical.com/about-us/',
} as const;

export const PRODUCTION_BASES: ProductionBase[] = [
  {
    entity: 'Mingda (Bangladesh) New Material Co., Ltd.',
    city: 'BEPZA Economic Zone, Mirsharai, Chattogram',
    country: 'Bangladesh',
    note: 'USD 76.41 million investment · 500+ local jobs',
    primary: true,
  },
  {
    entity: 'Hubei Hongxing Hongda New Materials Co., Ltd.',
    city: 'Jingmen, Hubei Province',
    country: 'China',
    note: '200,000 t/yr water-based emulsion · 5,000 t/yr VDC copolymer',
  },
  {
    entity: 'Weixian Shuangying Chemical Industry Co., Ltd.',
    city: 'Xingtai, Hebei Province',
    country: 'China',
  },
  {
    entity: 'Sichuan Jinyuanda Technology Co., Ltd.',
    city: 'Meishan, Sichuan Province',
    country: 'China',
  },
];

/** Bangladesh-specific facts, all sourced from the company news archive. */
export const BANGLADESH = {
  entity: 'Mingda (Bangladesh) New Material Co., Ltd.',
  zone: 'BEPZA Economic Zone, Mirsharai, Chattogram',
  investmentUsd: 76_410_000,
  investmentLabel: 'USD 76.41 M',
  jobs: 500,
  signedOn: '8 January 2024',
  witness:
    'Signing witnessed by BEPZA Executive Chairman Major General Abul Kalam Mohammad Ziaur Rahman',
  source:
    'https://www.hxhdchemical.com/news/hongxing-hongda-will-establish-a-new-plant-in-bangladesh/',
} as const;

/** Verified capability figures for the group's flagship Chinese plant. */
export const CAPACITY = [
  { value: '200,000', unit: 't/yr', label: 'Water-based emulsion', scope: 'Hubei plant' },
  { value: '5,000', unit: 't/yr', label: 'VDC copolymer emulsion', scope: 'Hubei plant' },
  { value: '16', unit: 'lines', label: 'Automatic emulsion lines', scope: 'Hubei plant' },
  { value: '4', unit: 'lines', label: 'VDC copolymer lines', scope: 'Hubei plant' },
];

export const MILESTONES = [
  {
    year: '2000',
    title: 'Hongxing Hongda founded',
    body: 'Established as a chemical group integrating R&D, production, sales and after-sales service of emulsions and coatings.',
  },
  {
    year: '2021',
    title: 'CNY 1.6 bn expansion announced',
    body: 'CNY 1.1 bn for 400,000 t/yr water-based and 60,000 t/yr butadiene emulsion, plus CNY 500 m for 50,000 t/yr vinylidene chloride copolymer emulsion.',
    source:
      'https://www.hxhdchemical.com/news/hongxing-hongda-plans-to-invest-1-6-billion-yuan-to-build-a-new-emulsion-production-plant-with-output-capacity-510000-tons-year/',
  },
  {
    year: '2023',
    title: 'Strategic cooperation with Keshun Waterproof Technology',
    body: 'Agreement for in-depth cooperation in waterproof coatings, following a technical review of Hongxing Hongda production facilities.',
    source:
      'https://www.hxhdchemical.com/news/hongxing-hongda-cooperates-with-keshun-waterproof-technology-co-ltd-to-bring-a-new-future-of-the-industry/',
  },
  {
    year: '2024',
    title: 'Bangladesh plant agreement signed',
    body: 'USD 76.41 million committed with Mingda to build a plant in the BEPZA Economic Zone, Mirsharai, Chattogram — creating 500+ local positions.',
    source:
      'https://www.hxhdchemical.com/news/hongxing-hongda-will-establish-a-new-plant-in-bangladesh/',
  },
  {
    year: '2025',
    title: 'China Coating Show 2025',
    body: 'Exhibited across the three-day China Coating Show, presenting the emulsion and waterproofing portfolio.',
    source:
      'https://www.hxhdchemical.com/news/the-three-day-china-coating-show-2025-came-to-a-successful-conclusion/',
  },
];
