/**
 * Company facts researched from hxhdchemical.com (about-us, news archive) and
 * verified 2026-08-09. Every figure below is sourced — do not add numbers here
 * that cannot be traced to `source`.
 */

export interface ProductionBase {
  entity: string;
  city: string;
  country: 'China' | 'Bangladesh';
  note?: string;
  primary?: boolean;
}

export const COMPANY = {
  group: 'Hongxing Hongda',
  /**
   * This site belongs to the Bangladesh entity, so `legalName` is the
   * Bangladesh company — not the Hubei one, which is a separate member of the
   * group and appears in GROUP_COMPANIES below.
   */
  legalName: 'Hongxing Hongda (BD) Two Win Technology Co., Ltd.',
  founded: 2000,
  /**
   * Contact address for this site. Split into lines so the footer and contact
   * page can break it identically without re-typing it. `headOffice` is the
   * one-line form for metadata and plain-text contexts.
   */
  address: {
    line1: 'House-51, Road No.-07',
    line2: 'Nikunja-1, Dhaka-1229',
    country: 'Bangladesh',
  },
  headOffice: 'House-51, Road No.-07, Nikunja-1, Dhaka-1229, Bangladesh',
  phone: '+880 1335 203691',
  phoneHref: '+8801335203691',
  /**
   * Designated enquiry address for this site. Import COMPANY.email rather than
   * hardcoding it — every page, form and footer reads from here.
   * (The address published on hxhdchemical.com is hxhdchem@163.com; this
   * inbox supersedes it for enquiries generated by this site.)
   */
  email: 'hongxinghongda7@gmail.com',
  sourceUrl: 'https://www.hxhdchemical.com/about-us/',
} as const;

/**
 * Every form on the site (enquiry, newsletter, resource sign-up) is delivered
 * to BOTH of these inboxes. There is no backend, so forms open a pre-composed
 * mail draft addressed to this list — see `mailtoHref` below.
 *
 * Order matters only cosmetically: the first address is what a mail client
 * shows as the primary recipient. Add or remove entries here and every form
 * picks it up; do not hardcode recipients in components.
 */
export const FORM_RECIPIENTS = [
  'hongxinghongda7@gmail.com',
  'dibbodutta06@gmail.com',
] as const;

/**
 * Builds a `mailto:` URL addressed to all FORM_RECIPIENTS.
 *
 * RFC 6068 allows a comma-separated address list in the `to` part, which Gmail,
 * Outlook, Apple Mail and Thunderbird all honour. The addresses themselves are
 * NOT percent-encoded — encoding the separating commas is what breaks multi-
 * recipient drafts in several clients. Subject and body are encoded normally.
 */
export function mailtoHref(subject: string, body: string): string {
  const to = FORM_RECIPIENTS.join(',');
  const query = `subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  return `mailto:${to}?${query}`;
}

export const PRODUCTION_BASES: ProductionBase[] = [
  {
    entity: 'Hongxing Hongda (BD) Two Win Technology Co., Ltd.',
    city: 'BEPZA Economic Zone, Mirsharai, Chattogram',
    country: 'Bangladesh',
    note: 'USD 76.41 million investment · 500+ local jobs',
    primary: true,
  },
  {
    entity: 'Hubei Hongxing Hongda New Materials Co., Ltd.',
    city: 'Jingmen, Hubei Province',
    country: 'China',
    note: '200,000 t/yr water-based emulsion · 5,000 t/yr VDC copolymer',
  },
  {
    entity: 'Weixian Shuangying Chemical Industry Co., Ltd.',
    city: 'Xingtai, Hebei Province',
    country: 'China',
  },
  {
    entity: 'Sichuan Jinyuanda Technology Co., Ltd.',
    city: 'Meishan, Sichuan Province',
    country: 'China',
  },
];

/** Bangladesh-specific facts, all sourced from the company news archive. */
export const BANGLADESH = {
  entity: 'Hongxing Hongda (BD) Two Win Technology Co., Ltd.',
  zone: 'BEPZA Economic Zone, Mirsharai, Chattogram',
  investmentUsd: 76_410_000,
  investmentLabel: 'USD 76.41 M',
  jobs: 500,
  signedOn: '8 January 2024',
  witness:
    'Signing witnessed by BEPZA Executive Chairman Major General Abul Kalam Mohammad Ziaur Rahman',
  source:
    'https://www.hxhdchemical.com/news/hongxing-hongda-will-establish-a-new-plant-in-bangladesh/',
} as const;

/** Verified capability figures for the group's flagship Chinese plant. */
export const CAPACITY = [
  { value: '200,000', unit: 't/yr', label: 'Water-based emulsion', scope: 'Hubei plant' },
  { value: '5,000', unit: 't/yr', label: 'VDC copolymer emulsion', scope: 'Hubei plant' },
  { value: '16', unit: 'lines', label: 'Automatic emulsion lines', scope: 'Hubei plant' },
  { value: '4', unit: 'lines', label: 'VDC copolymer lines', scope: 'Hubei plant' },
];

export const MILESTONES = [
  {
    year: '2000',
    title: 'Hongxing Hongda founded',
    body: 'Established as a chemical group integrating R&D, production, sales and after-sales service of emulsions and coatings.',
  },
  {
    year: '2021',
    title: 'CNY 1.6 bn expansion announced',
    body: 'CNY 1.1 bn for 400,000 t/yr water-based and 60,000 t/yr butadiene emulsion, plus CNY 500 m for 50,000 t/yr vinylidene chloride copolymer emulsion.',
    source:
      'https://www.hxhdchemical.com/news/hongxing-hongda-plans-to-invest-1-6-billion-yuan-to-build-a-new-emulsion-production-plant-with-output-capacity-510000-tons-year/',
  },
  {
    year: '2023',
    title: 'Strategic cooperation with Keshun Waterproof Technology',
    body: 'Agreement for in-depth cooperation in waterproof coatings, following a technical review of Hongxing Hongda production facilities.',
    source:
      'https://www.hxhdchemical.com/news/hongxing-hongda-cooperates-with-keshun-waterproof-technology-co-ltd-to-bring-a-new-future-of-the-industry/',
  },
  {
    year: '2025',
    title: 'China Coating Show 2025',
    body: 'Exhibited across the three-day China Coating Show, presenting the emulsion and waterproofing portfolio.',
    source:
      'https://www.hxhdchemical.com/news/the-three-day-china-coating-show-2025-came-to-a-successful-conclusion/',
  },
];

/**
 * The companies that make up the group, as listed on the corporate plaque.
 *
 * Names are reproduced exactly as written there, including the spacing of
 * "(BD) Two Win" — they are legal entity names, so they are not translated or
 * tidied. `country` is ours, added so the list can be grouped or filtered.
 */
export interface GroupCompany {
  name: string;
  country: string;
  /** The entity this website belongs to. */
  isThisSite?: boolean;
}

export const GROUP_COMPANIES: GroupCompany[] = [
  { name: 'Beijing Xinda Shiji New Materials Co., Ltd', country: 'China' },
  { name: 'Weixian Shuangying Chemical Industry Co., Ltd', country: 'China' },
  { name: 'Hubei Hongxing Hongda New Materials Co., Ltd', country: 'China' },
  {
    name: 'Hongxing Hongda (BD) Two Win Technology Co., Ltd',
    country: 'Bangladesh',
    isThisSite: true,
  },
  { name: 'Hongxing Hongda (Cambodia) Co., Ltd', country: 'Cambodia' },
  { name: 'Golden Coast Opus Ltd (Ghana)', country: 'Ghana' },
  { name: 'Hongxing Hongda (Nigeria) Co., Ltd', country: 'Nigeria' },
];
